interface ErrorMessages {
  [code: string]: string;
}

const errorMessages: ErrorMessages = {
  9999: 'Invalid Role',
  1000: 'Auth header is missing',
  1001: 'Auth token required',
  2000: 'Name, email, and password are required for signup.',
  2001: 'Model with this email already exists',
  2003: 'Model has been successfully added.',
  2004: 'Email or username is required',
  2005: 'Password is missing',
  2006: 'Invalid email or password',
  2007: 'Email has been updated',
  2008: 'Invalid Source',
  2009: 'Unable to send verification email.',
  2010: 'Email verification has been sent.',
  2011: 'Email and verification code are required.',
  2012: 'Invalid Verification code',
  2013: 'Model email has been verified.',
  2014: 'Basic details are required for model onboarding',
  2015: 'Model languages are required',
  2016: 'Model ID is invalid.',
  2017: 'Documents are required for model onboarding',
  2018: 'Image url absent',
  2019: "The 'is_document' flag is required",
  2020: 'Please upload at least 2 photos. Sorry, you can upload 30 pictures only.',
  2021: 'Invalid verification step',
  2022: 'Invalid email',
  2023: 'Unable to send reset password email.',
  2024: 'Please enter a valid password to change your current password',
  2025: 'Please enter a valid password for setting new password',
  2026: 'Invalid model photo id',
  2027: 'Price per minute is required',
  2028: 'Please end the ongoing call to update the price',
  2029: 'Username is required to fetch model details',
  2030: 'Model username not found',
  2031: 'Amount is required for payout',
  2032: 'Bank account details are required',
  2033: 'Insufficient amount for withdrawal',
  2034: 'Your wallet amount is less than the minimum withdrawal amount',
  2035: 'Bank details are required',
  2036: 'File ID is required.',
  2037: 'Model ID is required.',
  2038: 'Model profile status is invalid.',
  2039: 'Model rejection reason is required.',
  2040: 'Model not found',
  2041: "Model's profile status must be 'In Review' to reject",
  3001: 'Name, email & password required',
  3002: 'User with this email already exists',
  3003: 'Customer email or username is required',
  3004: 'Customer password missing',
  3005: 'Invalid email or password',
  3006: 'Unable to send password reset email',
  3007: 'Email or verification code invalid',
  3008: 'Customer with email or id not found',
  3009: 'Unable to send verification email',
  3010: 'Email & verification code are required',
  3011: 'Customer id invalid',
  3012: 'Please enter a valid password to change your current password',
  3013: 'Model is already added to your favourites',
  4001: 'Customer plan id required',
  5001: 'Notification id invalid',
  5002: 'Username exists',
  6001: 'Invalid call status',
  6002: 'Call has ended',
  6003: 'You do not have enough credits to make this call',
  7001: 'Price required',
  7002: 'Price exists',
  7003: 'Withdrawal amount is required',
  7004: 'Withdrawal amount exists',
  7005: 'Commission percentage required',
  7006: 'Commission already exists',
  7007: 'Payout Id required',
  7008: 'Payout is approved',
  7009: 'Insufficient wallet balance to process a payout',
  7010: 'Admin details are required',
  7011: 'Admin exists',
  7012: 'Invalid admin details',
  7013: 'Enter a valid admin email',
  7014: 'Reset password email not sent',
  7015: 'Admin password required',
  7016: 'Admin exchange rate id required'
};

export default errorMessages;
